# Generated by Django 4.1.7 on 2023-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_link', models.TextField(blank=True, null=True)),
                ('photo1', models.TextField(blank=True, null=True)),
                ('photo2', models.TextField(blank=True, null=True)),
                ('photo3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
    ]
